# Generated by Django 4.0 on 2022-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(choices=[('GENERAL', 'GENERAL'), ('DEVELOPER', 'DEVELOPER'), ('DESK_AND_DASHBOARD', 'DESK_AND_DASHBOARD')], default='GENERAL', max_length=30)),
                ('term', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attached_link', models.URLField(blank=True, null=True)),
                ('examples', models.TextField(blank=True, null=True)),
                ('sendbird_usage', models.PositiveSmallIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
